
var util = require('utils/util.js');

App({
  globalData: {
    version: 'v2.6.0',
    is_login: false,
    user_id: 0,
    user_name: "",
    money: 0,
    email: "",
    phone: "",
    referal_id: "",
    API_HOME: "https://touacar.com/api/index.php/home/",
    API_ARTICLE: "https://touacar.com/api/index.php/article/lists/cid/",
    API_ARTICLE_DETIAL: "https://touacar.com/api/index.php/article/detail/cid/",
    API_PROJECT: "https://touacar.com/api/index.php/project/lists/",
    API_PROJECT_DETIAL: "https://touacar.com/api/index.php/project/detail/id/",
    API_APPLY: "https://touacar.com/api/index.php/apply",
    API_APPLY_APPLY: "https://touacar.com/api/index.php/apply/apply",
    API_ORDER: "https://touacar.com/api/index.php/order",
    API_ORDER_DETIAL: "https://touacar.com/api/index.php/order/detail/id/",
    API_FINANCE: "https://touacar.com/api/index.php/finance",
    API_CHARGE_WECHAT: "https://touacar.com/api/index.php/charge/wechat",
    API_CHARGE_CARD: "https://touacar.com/api/index.php/charge/card",
    API_QRCODE: "https://touacar.com/api/index.php/qrcode",
    API_LOGIN: "https://touacar.com/api/index.php/login/login",
    API_LOGIN_WECHAT: "https://touacar.com/api/index.php/login/login_wechat",
    API_LOGOUT: "https://touacar.com/api/index.php/logout",
    API_REGISER_EMAIL: "https://touacar.com/api/index.php/register/check_email_ajax",
    API_REGISER_PHONE: "https://touacar.com/api/index.php/register/check_phone_ajax",
    API_ACTIVE_EMAIL: "https://touacar.com/api/index.php/register/user_active_byemail",
    API_ACTIVE_PHONE: "https://touacar.com/api/index.php/register/user_active_byphone",
    API_SETTING_PW: "https://touacar.com/api/index.php/register/setting_pw",
    API_CHECK_WECHAT: "https://touacar.com/api/me/me/check_wechat",
    API_CHECK_WECHAT_BG: "https://touacar.com/api/me/me/check_wechat_bg",
    API_WITHDRAWAL: "https://touacar.com/api/index.php/withdrawal/withdrawal",
    API_WITHDRAWAL_CHECK: "https://touacar.com/api/index.php/withdrawal/check",
    API_WITHDRAWAL_GET_SMS: "https://touacar.com/api/index.php/withdrawal/get_sms_code",
    API_AUTHENTIC_PHONE: "https://touacar.com/api/index.php/authentic_phone/binding_phone",
    API_AUTHENTIC_PHONE_GET_SMS: "https://touacar.com/api/index.php/authentic_phone/get_sms_code",
    API_AUTHENTIC_PHONE_BIND: "https://touacar.com/api/index.php/authentic_phone/bindPhone",
    API_AUTHENTIC_NAME: "https://touacar.com/api/index.php/authentic_name/checking",
    API_AUTHENTIC_NAME_CER: "https://touacar.com/api/index.php/authentic_name/certificate",
    API_AUTHENTIC_EMAIL: "https://touacar.com/api/index.php/authentic_email/bindEmail",
    API_AUTHENTIC_EMAIL_BIND: "https://touacar.com/api/index.php/authentic_email/check_bindEmail",
    API_AUTHENTIC_EMAIL_UPDATE: "https://touacar.com/api/index.php/authentic_email/check_email",
    API_AUTHENTIC_EMAIL_UNBIND: "https://touacar.com/api/index.php/authentic_email/check_new_email",
    API_AUTHENTIC_EMAIL_BIND_NEW: "https://touacar.com/api/index.php/authentic_email/send_new_email",
    API_AUTHENTIC_EMAIL_CHICK_NEW: "https://touacar.com/api/index.php/authentic_email/check_new_bind",
    API_AUTHENTIC_PHONE_UPDATE: "https://touacar.com/api/index.php/authentic_phone/changeBindOldPhone",
    API_AUTHENTIC_PHONE_UPDATE_GET_SMS: "https://touacar.com/api/index.php/authentic_phone/get_old_sms_code",
    API_AUTHENTIC_PHONE_UPDATE_GET_NEW_SMS: "https://touacar.com/api/index.php/authentic_phone/get_new_sms_code",
    API_AUTHENTIC_PHONE_UPDATE_BIND_NEW: "https://touacar.com/api/index.php/authentic_phone/changeBindNewPhone",
    API_REFRESH: "https://touacar.com/api/index.php/login/refresh",
    API_APPLY_EMAIL_CHECK: "https://touacar.com/api/index.php/apply/check_email",
    BASE_URL: "https://touacar.com/",

    API_RES: "https://piggycars.com/assets/image/car",
    API_CARS: "https://piggycars.com/api/catalog/vehicle/get_list",

  },
  onLaunch(options) {
    wx.hideTabBar({
      aniamtion: false,
      success: function (res) { },
      fail: function (res) { },
      complete: function (res) { },
    })
    util.checkUpdateVersion();
  }
})