
App({
  globalData: {
    version: 'v1.4.9',
    is_login: false,
    user_id: "",
    username: "",
    password: "",
    email: "",
    country_code: "1",
    phone_local: "",
    phone: "",
    code: "",
    openid: "",
    first_name: "",
    last_name: "",
    address: {},
    id_images: [],
    filter_params: {},
    order_id: 0,
    checkout_id: 0,
    checkout_year: "",
    checkout_make: "",
    checkout_model: "",
    checkout_image: "",
    checkout_payment_down: 0,
    checkout_payment_down_tax: 0,
    checkout_payment_down_total: 0,
    API_LOGIN: "https://api.piggycars.net/account/login",
    API_WECHAT_LOGIN: "https://api.piggycars.net/account/login/with",
    API_WECHAT_REGISTER: "https://api.piggycars.net/account/register/with",
    API_LOGOUT: "https://api.piggycars.net/account/logout",
    API_REGISTER: "https://api.piggycars.net/account/register",
    API_USER: "https://api.piggycars.net/account/user",
    API_PASSWORD: "https://api.piggycars.net/account/reset",
    API_SMS: "https://api.piggycars.net/account/validation/send_code",
    API_ADDR: "https://api.piggycars.net/account/register/contact",
    API_ID: "https://api.piggycars.net/account/register/get_identity",
    API_ID_UPLOAD: "https://api.piggycars.net/account/register/identity",
    API_CONFIRM: "https://api.piggycars.net/checkout/confirm",
    API_CARD: "https://api.piggycars.net/extension/payment/stripe",
    //API_WECHAT_AUTH: "https://api.piggycars.net/checkout/confirm/wechat_auth",

    API_WECHAT_AUTH: "https://api.piggycars.net/extension/payment/hantepay",


    API_CARS: "https://api.piggycars.net/catalog/vehicle/get_list",
    API_CAR: "https://api.piggycars.net/catalog/vehicle",
    API_FILTERS: "https://api.piggycars.net/catalog/filters",
    API_CATEGORIES: "https://api.piggycars.net/catalog/filters/category",
    API_ORDER: "https://api.piggycars.net/sales/order/get_list",
    API_BLOGS: "https://piggycars.net/info/article/get_list",
    API_BLOG_DETAIL: "https://piggycars.net/info/article/json/",
    API_LANG: "https://api.piggycars.net/common/language?lang=chinese&no_redirect=1",
    API_RES: "https://piggycars.com/api/assets/image",
    API_RES_INFO: "https://piggycars.com/assets/image"
  }
})